#!/bin/sh


SHOWCURSOR="yes"
KEYBOARD_APPLET="keyboard"

matchbox-desktop &

# Lines containing feature-[foo] are removed at build time if the machine
# doesn't have the feature "foo".

START_APPLETS=showdesktop,windowselector
END_APPLETS=$KEYBOARD_APPLET,systray,startup-notify,notify
END_APPLETS=battery,$END_APPLETS # feature-acpi
END_APPLETS=battery,$END_APPLETS # feature-apm
END_APPLETS=clock,$END_APPLETS
END_APPLETS=openmoko-panel-gsm,$END_APPLETS # feature-phone

matchbox-panel --start-applets $START_APPLETS --end-applets $END_APPLETS &

exec matchbox-window-manager -theme Sato -use_cursor $SHOWCURSOR $@
